"""fix enum role user

Revision ID: 32010f177736
Revises: 3d6f7cd2f7d4
Create Date: 2026-05-06 11:07:10.280041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32010f177736'
down_revision = '3d6f7cd2f7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['traite_par'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['demandeur_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['responsable_id'], ['id'])

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(None, 'materiels', ['materiel_id'], ['id'])

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categories_materiel', ['categorie_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(None, 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
