"""ajout inventaire employes

Revision ID: 33d1c5efab61
Revises: b274b56f7ac8
Create Date: 2026-07-27 10:02:33.595370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d1c5efab61'
down_revision = 'b274b56f7ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventaire_employes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], name=op.f('fk_inventaire_employes_demande_id_demandes')),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], name=op.f('fk_inventaire_employes_departement_id_departements')),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], name=op.f('fk_inventaire_employes_entreprise_id_entreprises')),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiels.id'], name=op.f('fk_inventaire_employes_materiel_id_materiels')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventaire_employes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventaire_employes')),
    sa.UniqueConstraint('user_id', 'materiel_id', name='_user_materiel_uc')
    )
    with op.batch_alter_table('inventaire_employes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventaire_employes_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventaire_employes_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventaire_employes_materiel_id'), ['materiel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventaire_employes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_categories_materiel_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_demandes_demandeur_id_users'), 'users', ['demandeur_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_responsable_id_users'), 'users', ['responsable_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_traite_par_users'), 'users', ['traite_par'], ['id'])

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_departements_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('historique_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_historique_actions_entreprise_id_entreprises'))
        batch_op.drop_index(batch_op.f('fk_historique_actions_user_id_users'))
        batch_op.create_foreign_key(batch_op.f('fk_historique_actions_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_historique_actions_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_lignes_demande_demande_id_demandes'), 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_lignes_demande_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_materiels_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_materiels_categorie_id_categories_materiel'), 'categories_materiel', ['categorie_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_materiels_departement_id_departements'), 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_demande_id_demandes'), 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_notifications_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_notifications_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_notifications_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_responsable_departements_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_responsable_departements_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_stocks_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stocks_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stocks_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_entreprises_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_entreprises_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_users_departement_id_departements'), 'departements', ['departement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_departement_id_departements'), type_='foreignkey')

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_entreprises_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_entreprises_entreprise_id_entreprises'), type_='foreignkey')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stocks_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stocks_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stocks_departement_id_departements'), type_='foreignkey')

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_responsable_departements_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_responsable_departements_departement_id_departements'), type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_sender_id_users'), type_='foreignkey')

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_demande_id_demandes'), type_='foreignkey')

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_materiels_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_materiels_categorie_id_categories_materiel'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_materiels_entreprise_id_entreprises'), type_='foreignkey')

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lignes_demande_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_lignes_demande_demande_id_demandes'), type_='foreignkey')

    with op.batch_alter_table('historique_actions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_historique_actions_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_historique_actions_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_historique_actions_user_id_users'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_historique_actions_entreprise_id_entreprises'), ['entreprise_id'], unique=False)

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_departements_entreprise_id_entreprises'), type_='foreignkey')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_demandes_traite_par_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_responsable_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_demandeur_id_users'), type_='foreignkey')

    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_materiel_entreprise_id_entreprises'), type_='foreignkey')

    with op.batch_alter_table('inventaire_employes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventaire_employes_user_id'))
        batch_op.drop_index(batch_op.f('ix_inventaire_employes_materiel_id'))
        batch_op.drop_index(batch_op.f('ix_inventaire_employes_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_inventaire_employes_departement_id'))

    op.drop_table('inventaire_employes')
    # ### end Alembic commands ###
