"""initial migration

Revision ID: 985530be00d2
Revises: 
Create Date: 2026-05-06 10:18:16.456104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985530be00d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entreprises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entreprises_code'), ['code'], unique=True)

    op.create_table('categories_materiel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'entreprise_id', name='_nom_entreprise_uc')
    )
    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_materiel_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('departements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'entreprise_id', name='_code_entreprise_uc')
    )
    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departements_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_departements_entreprise_id'), ['entreprise_id'], unique=False)

    op.create_table('materiels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_materiel.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiels_categorie_id'), ['categorie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiels_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiels_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiels_reference'), ['reference'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYE', 'RESPONSABLE', 'MAGASINIER', 'ADMIN', 'SUPER_ADMIN', name='roleuser'), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('demandes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('demandeur_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('traite_par', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'SOUMISE', 'EN_TRAITEMENT', 'APPROUVEE1', 'APPROUVEE2', 'REJETEE1', 'REJETEE2', 'EN_ATTENTE_STOCK', 'LIVREE', name='statutdemande'), nullable=False),
    sa.Column('justification', sa.String(length=500), nullable=True),
    sa.Column('motif_rejet', sa.String(length=500), nullable=True),
    sa.Column('date_soumission', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_traitement', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['demandeur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traite_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandes_demandeur_id'), ['demandeur_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demandes_reference'), ['reference'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ERROR', name='typenotification'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('responsable_departements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'departement_id', name='_user_departement_uc')
    )
    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsable_departements_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsable_departements_user_id'), ['user_id'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('quantite_actuelle', sa.Integer(), nullable=False),
    sa.Column('seuil_alerte', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materiel_id', 'departement_id', name='_materiel_departement_uc')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_materiel_id'), ['materiel_id'], unique=False)

    op.create_table('user_entreprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('role_entreprise', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_entreprises_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_entreprises_user_id'), ['user_id'], unique=False)

    op.create_table('lignes_demande',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.Column('qte_demandee', sa.Integer(), nullable=False),
    sa.Column('qte_accordee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_demande_demande_id'), ['demande_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lignes_demande_materiel_id'), ['materiel_id'], unique=False)

    op.create_table('mouvements_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_mouvement', sa.Enum('ENTREE', 'SORTIE', name='typemouvement'), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('date_mouvement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mouvements_stock_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mouvements_stock_entreprise_id'), ['entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mouvements_stock_materiel_id'), ['materiel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mouvements_stock_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mouvements_stock_user_id'))
        batch_op.drop_index(batch_op.f('ix_mouvements_stock_materiel_id'))
        batch_op.drop_index(batch_op.f('ix_mouvements_stock_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_mouvements_stock_departement_id'))

    op.drop_table('mouvements_stock')
    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_demande_materiel_id'))
        batch_op.drop_index(batch_op.f('ix_lignes_demande_demande_id'))

    op.drop_table('lignes_demande')
    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_entreprises_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_entreprises_entreprise_id'))

    op.drop_table('user_entreprises')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_materiel_id'))
        batch_op.drop_index(batch_op.f('ix_stocks_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_stocks_departement_id'))

    op.drop_table('stocks')
    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsable_departements_user_id'))
        batch_op.drop_index(batch_op.f('ix_responsable_departements_departement_id'))

    op.drop_table('responsable_departements')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_entreprise_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_reference'))
        batch_op.drop_index(batch_op.f('ix_demandes_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_departement_id'))
        batch_op.drop_index(batch_op.f('ix_demandes_demandeur_id'))

    op.drop_table('demandes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiels_reference'))
        batch_op.drop_index(batch_op.f('ix_materiels_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_materiels_departement_id'))
        batch_op.drop_index(batch_op.f('ix_materiels_categorie_id'))

    op.drop_table('materiels')
    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departements_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_departements_code'))

    op.drop_table('departements')
    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_materiel_entreprise_id'))

    op.drop_table('categories_materiel')
    with op.batch_alter_table('entreprises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entreprises_code'))

    op.drop_table('entreprises')
    # ### end Alembic commands ###
