"""ajout de la table historique_actions

Revision ID: b274b56f7ac8
Revises: 7a1e457d047b
Create Date: 2026-06-29 16:28:06.841993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b274b56f7ac8'
down_revision = '7a1e457d047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ON GARDE EXCLUSIVEMENT LA CRÉATION DE LA TABLE HISTORIQUE
    op.create_table('historique_actions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entreprise_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('table_cible', sa.String(length=100), nullable=False),
        sa.Column('id_cible', sa.Integer(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], name=op.f('fk_historique_actions_entreprise_id_entreprises')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_historique_actions_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_historique_actions'))
    )
    
    # Tout le reste a été supprimé pour éviter les collisions avec ta base existante !
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ON SUPPRIME UNIQUEMENT LA TABLE D'HISTORIQUE EN CAS DE DOWNGRADE
    op.drop_table('historique_actions')
    
    # Tout le reste a été supprimé pour protéger tes tables existantes
    # ### end Alembic commands ###
