"""...

Revision ID: c246478dd59e
Revises: 33d1c5efab61
Create Date: 2026-08-05 10:39:25.494500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c246478dd59e'
down_revision = '33d1c5efab61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_categories_materiel_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_demandes_responsable_id_users'))
        batch_op.drop_index(batch_op.f('fk_demandes_traite_par_users'))
        batch_op.create_foreign_key(batch_op.f('fk_demandes_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_traite_par_users'), 'users', ['traite_par'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_responsable_id_users'), 'users', ['responsable_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_demandes_demandeur_id_users'), 'users', ['demandeur_id'], ['id'])

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_departements_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('historique_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_historique_actions_entreprise_id_entreprises'))
        batch_op.drop_index(batch_op.f('fk_historique_actions_user_id_users'))
        batch_op.create_foreign_key(batch_op.f('fk_historique_actions_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_historique_actions_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('inventaire_employes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_inventaire_employes_demande_id_demandes'))
        batch_op.create_foreign_key(batch_op.f('fk_inventaire_employes_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inventaire_employes_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inventaire_employes_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inventaire_employes_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inventaire_employes_demande_id_demandes'), 'demandes', ['demande_id'], ['id'])

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_lignes_demande_demande_id_demandes'), 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_lignes_demande_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_materiels_categorie_id_categories_materiel'), 'categories_materiel', ['categorie_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_materiels_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_materiels_departement_id_departements'), 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_mouvements_stock_demande_id_demandes'))
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_demande_id_demandes'), 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_mouvements_stock_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_notifications_sender_id_users'))
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_notifications_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_notifications_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_notifications_departement_id_departements'), 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_responsable_departements_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_responsable_departements_departement_id_departements'), 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_stocks_departement_id_departements'), 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stocks_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stocks_materiel_id_materiels'), 'materiels', ['materiel_id'], ['id'])

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_entreprises_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_entreprises_entreprise_id_entreprises'), 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_users_departement_id_departements'))
        batch_op.create_foreign_key(batch_op.f('fk_users_departement_id_departements'), 'departements', ['departement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_departement_id_departements'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_users_departement_id_departements'), ['departement_id'], unique=False)

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_entreprises_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_entreprises_user_id_users'), type_='foreignkey')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stocks_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stocks_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stocks_departement_id_departements'), type_='foreignkey')

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_responsable_departements_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_responsable_departements_user_id_users'), type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_sender_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_notifications_sender_id_users'), ['sender_id'], unique=False)

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_mouvements_stock_demande_id_demandes'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_mouvements_stock_demande_id_demandes'), ['demande_id'], unique=False)

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_materiels_departement_id_departements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_materiels_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_materiels_categorie_id_categories_materiel'), type_='foreignkey')

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lignes_demande_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_lignes_demande_demande_id_demandes'), type_='foreignkey')

    with op.batch_alter_table('inventaire_employes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventaire_employes_demande_id_demandes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inventaire_employes_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inventaire_employes_materiel_id_materiels'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inventaire_employes_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inventaire_employes_departement_id_departements'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_inventaire_employes_demande_id_demandes'), ['demande_id'], unique=False)

    with op.batch_alter_table('historique_actions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_historique_actions_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_historique_actions_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_historique_actions_user_id_users'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_historique_actions_entreprise_id_entreprises'), ['entreprise_id'], unique=False)

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_departements_entreprise_id_entreprises'), type_='foreignkey')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_demandes_demandeur_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_responsable_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_traite_par_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_entreprise_id_entreprises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_demandes_departement_id_departements'), type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_demandes_traite_par_users'), ['traite_par'], unique=False)
        batch_op.create_index(batch_op.f('fk_demandes_responsable_id_users'), ['responsable_id'], unique=False)

    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_materiel_entreprise_id_entreprises'), type_='foreignkey')

    # ### end Alembic commands ###
