"""update notification model

Revision ID: d0a8b3e01563
Revises: 036caff9d0ae
Create Date: 2026-06-16 10:21:19.916011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a8b3e01563'
down_revision = '036caff9d0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['demandeur_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['traite_par'], ['id'])
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['responsable_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(None, 'materiels', ['materiel_id'], ['id'])

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories_materiel', ['categorie_id'], ['id'])

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'demandes', ['demande_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departement_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_departement_id'), ['departement_id'], unique=False)
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])
        batch_op.create_foreign_key(None, 'materiels', ['materiel_id'], ['id'])
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'entreprises', ['entreprise_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_entreprises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('responsable_departements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_departement_id'))
        batch_op.drop_column('sender_id')
        batch_op.drop_column('departement_id')

    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('materiels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lignes_demande', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('departements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('demandes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('categories_materiel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
